### PR TITLE
idk, very big update

### PR DESCRIPTION
**Pull request by GenericGithUser**
new page of userdata has finally been designed it is composed of the profile page and the grade page, you can also modify/delete the profile there
here is some descriptions of the closed pull request
"To fully put the "management" in System Data Management, the "add a student" option has been created
In term with the option comes also a very long form for student addition"
Search results also now redirects user to created userdata page
other than that No UI changes

### CODE REVIEW

**Comment by GenericGithUser** [comment]
will upload the sample database file later

**Comment by Tskk-dev** [comment]
will review more after you send the db file but lgtm

**Comment by GenericGithUser** [comment]
> will review more after you send the db file but lgtm

sorry for the delay. here's the db file https://drive.google.com/file/d/1sX6_h0lmrumTJ0UCMuw99Q47LJqzPWnP/view?usp=sharing. It currently has the tables that you've sent before and a table that contains 5 students with LRNs

**Comment by GenericGithUser** [comment]
New stuff committed please review if anything needs to be changed,

**Comment by Tskk-dev** [comment]
lgtm, will merge in a bit

**Pull request merged**
